Обновление дизайна
1ldaun/al-catan pull request #2
Opened 2022-10-19 20:36 UTC by Bula2

2022-10-20 01:09 UTC, Bula2 commented
Короче, я чуть чуть подкорректировал адаптив в некоторых места, не знаю насколько лучше стало, но вроде, как минимум, не сильно хуже

2022-10-20 01:11 UTC, Bula2 commented
+ Добавил кнопочки новые, но они пока пустые, потому что тестить надо с бэком, типо, будет ли зачищаться массив ходов или не будет и тп, так что пока не мерги, завтра доделаю

2022-10-20 21:18 UTC, Bula2 commented
Особое внимание прошу уделить адаптиву, вообще в нем не уверен

2022-10-21 08:30 UTC, 1ldaun requested changes

2022-10-21 08:30 UTC, 1ldaun commented on src/main-page/GameField/GameFieldItem/GameFieldItem.tsx
> +  const colorPalette = {
По хорошему такие константы выносить в assets, и импортить оттуда

2022-10-21 08:30 UTC, 1ldaun commented on src/main-page/GameField/GameField.tsx
> +        <div ref={myRef}></div>
Указать бы в названии рефа, что это якорь, а то непонятно зачем он

2022-10-21 08:30 UTC, 1ldaun commented on src/main-page/MainPage.tsx
> +          {firstStart ?
Вынести бы в отдельную функцию renderButtons

2022-10-21 19:18 UTC, 1ldaun approved these changes

2022-10-21 19:35 UTC, merged